spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: devaharish
    password: devaharish

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true